# Generated by Django 5.0.3 on 2024-03-18 04:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('room_reservation_id', models.UUIDField()),
                ('night_of_stay', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Booking'), (2, 'Cancellation')])),
                ('event_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('hotel_id', models.PositiveIntegerField()),
            ],
        ),
    ]
