# Generated by Django 5.0.3 on 2024-03-23 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_provider', '0003_rename_room_reservation_id_event_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='added_to_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
