# Generated by Django 5.0.3 on 2024-03-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_provider', '0004_event_added_to_dashboard_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
