# Generated by Django 5.0.3 on 2024-03-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_reservation_id', models.UUIDField()),
                ('night_of_stay', models.DateField()),
                ('status', models.PositiveSmallIntegerField()),
                ('event_timestamp', models.DateTimeField()),
                ('hotel_id', models.PositiveIntegerField()),
            ],
        ),
    ]
